openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'POC'
  license:
    name: MIT
servers:
  - url: '217.25.88.71:60494'
paths:
  /users:
    get:
      summary: 'Returns the list of all users'
      operationId: listUser
      responses:
        '200':
          description: 'List of users'
          headers:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
                  type: 404
                  message: 'Page not found'
  /signup:
    post:
      summary: 'Create a new user'
      responses:
        '200':
          description: 'New user has been crated'
        '400':
          description: 'No login or password provided'
  /login:
    post:
      

components:
  schemas:
    User:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
security:
  - BasicAuth: []